
psql:
  image: postgres:9.5
  environment:
    POSTGRES_USER: knowledge
    POSTGRES_PASSWORD: password
    POSTGRES_DB: knowledgebase
  ports:
    - "5432:5432"
  volumes_from:
    - psql_data
knowledge:
  image: koda/docker-knowledge
  links:
    - psql:psql
  expose:
    - "5000"
  ports:
    - "5000:8080"
  volumes_from:
    - data
