
psql_data:
  image: tianon/sleeping-beauty:latest
  volumes:
    - /var/lib/postgresql/data
data:
  image: tianon/sleeping-beauty:latest
  volumes:
    - /root/.knowledge
psql:
  image: postgres:9.5
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: password
    POSTGRES_DB: root
  ports:
    - "5432:5432"
  volumes_from:
    - psql_data
knowledge:
  image: koda/docker-knowledge
  links:
    - psql:psql
  expose:
    - "5000"
  ports:
    - "5000:8080"
  volumes_from:
    - data
